name: eeg_mi
channels:
  - conda-forge
  - bioconda
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
      - mne
prefix: /opt/anaconda3/envs/eeg_mi
